import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Js | Mohammad",
    default: "Home | Next Js | Mohammad",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen flex flex-col">
        <NavBar />
        <Suspense fallback={<Loading />}>
          <div className="flex justify-center items-center w-full h-full">
            {children}
          </div>
        </Suspense>

        <Footer />
      </body>
    </html>
  );
}
